# 1. LISTA DE FRASES COMUNES:
# Copia aquí frases largas o preguntas que aparecen en todos los documentos.
# El script las eliminará antes de comparar.
COMMON_PHRASES = [
    # Agrega frases específicas para tu TP aquí, por ejemplo:
    # "Answer the following questions",
]

# 2. MARCADORES DE FINALIZACIÓN DE DOCUMENTO:
# Si el script encuentra esto, ignorará todo lo que esté debajo de él.
END_MARKERS = [
    "bibliografía",
    "referencias bibliográficas",
    "bibliografia",
]

# 3. PALABRAS CLAVE EN ESPAÑOL (lista básica expandible)
STOP_WORDS_ES = [
    "de",
    "la",
    "que",
    "el",
    "en",
    "y",
    "a",
    "los",
    "del",
    "se",
    "las",
    "por",
    "un",
    "para",
    "con",
    "no",
    "una",
    "su",
    "al",
    "lo",
    "como",
    "más",
    "pero",
    "sus",
    "le",
    "ya",
    "o",
    "este",
    "sí",
    "porque",
    "esta",
    "entre",
    "cuando",
    "muy",
    "sin",
    "sobre",
    "también",
    "me",
    "hasta",
    "hay",
    "donde",
    "quien",
    "desde",
    "todo",
    "nos",
    "durante",
    "todos",
    "uno",
    "les",
    "ni",
    "contra",
    "otros",
    "ese",
    "eso",
    "ante",
    "ellos",
    "e",
    "esto",
    "mí",
    "antes",
    "algunos",
    "qué",
    "unos",
    "yo",
    "otro",
    "otras",
    "otra",
    "él",
    "tanto",
    "esa",
    "estos",
    "mucho",
    "quienes",
    "nada",
    "muchos",
    "cual",
    "poco",
    "ella",
    "estar",
    "estas",
    "algunas",
    "algo",
    "nosotros",
    "mi",
    "mis",
    "tú",
    "te",
    "ti",
    "tu",
    "tus",
    "ellas",
    "nosotras",
    "vosotros",
    "vosotras",
    "os",
    "mío",
    "mía",
    "míos",
    "mías",
    "tuyo",
    "tuya",
    "tuyos",
    "tuyas",
    "suyo",
    "suya",
    "suyos",
    "suyas",
    "nuestro",
    "nuestra",
    "nuestros",
    "nuestras",
    "vuestro",
    "vuestra",
    "vuestros",
    "vuestras",
    "es",
    "son",
    "fue",
    "era",
    "ser",
    "está",
    "están",
    "ha",
    "han",
    "hacer",
    "hace",
    "hizo",
    "tener",
    "tengo",
    "tiene",
    "tienen",
]


# --- CONFIGURACIÓN DE DEPURACIÓN ---
DEBUG_MODE = False  # Guarda el texto limpio en la carpeta debug/
